/*
Modern Logic Api

Manage and version your customer decision logic outside of your codebase

API version: 1.0.0
Contact: info@usemodernlogic.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package modern_logic_client

import (
	"encoding/json"
)

// ListResponse struct for ListResponse
type ListResponse struct {
	// Total number of entities
	Total *int32 `json:"total,omitempty"`
	// Total number of entities returned
	TotalReturned *int32 `json:"totalReturned,omitempty"`
	Items *[]map[string]interface{} `json:"items,omitempty"`
}

// NewListResponse instantiates a new ListResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListResponse() *ListResponse {
	this := ListResponse{}
	return &this
}

// NewListResponseWithDefaults instantiates a new ListResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListResponseWithDefaults() *ListResponse {
	this := ListResponse{}
	return &this
}

// GetTotal returns the Total field value if set, zero value otherwise.
func (o *ListResponse) GetTotal() int32 {
	if o == nil || o.Total == nil {
		var ret int32
		return ret
	}
	return *o.Total
}

// GetTotalOk returns a tuple with the Total field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListResponse) GetTotalOk() (*int32, bool) {
	if o == nil || o.Total == nil {
		return nil, false
	}
	return o.Total, true
}

// HasTotal returns a boolean if a field has been set.
func (o *ListResponse) HasTotal() bool {
	if o != nil && o.Total != nil {
		return true
	}

	return false
}

// SetTotal gets a reference to the given int32 and assigns it to the Total field.
func (o *ListResponse) SetTotal(v int32) {
	o.Total = &v
}

// GetTotalReturned returns the TotalReturned field value if set, zero value otherwise.
func (o *ListResponse) GetTotalReturned() int32 {
	if o == nil || o.TotalReturned == nil {
		var ret int32
		return ret
	}
	return *o.TotalReturned
}

// GetTotalReturnedOk returns a tuple with the TotalReturned field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListResponse) GetTotalReturnedOk() (*int32, bool) {
	if o == nil || o.TotalReturned == nil {
		return nil, false
	}
	return o.TotalReturned, true
}

// HasTotalReturned returns a boolean if a field has been set.
func (o *ListResponse) HasTotalReturned() bool {
	if o != nil && o.TotalReturned != nil {
		return true
	}

	return false
}

// SetTotalReturned gets a reference to the given int32 and assigns it to the TotalReturned field.
func (o *ListResponse) SetTotalReturned(v int32) {
	o.TotalReturned = &v
}

// GetItems returns the Items field value if set, zero value otherwise.
func (o *ListResponse) GetItems() []map[string]interface{} {
	if o == nil || o.Items == nil {
		var ret []map[string]interface{}
		return ret
	}
	return *o.Items
}

// GetItemsOk returns a tuple with the Items field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListResponse) GetItemsOk() (*[]map[string]interface{}, bool) {
	if o == nil || o.Items == nil {
		return nil, false
	}
	return o.Items, true
}

// HasItems returns a boolean if a field has been set.
func (o *ListResponse) HasItems() bool {
	if o != nil && o.Items != nil {
		return true
	}

	return false
}

// SetItems gets a reference to the given []map[string]interface{} and assigns it to the Items field.
func (o *ListResponse) SetItems(v []map[string]interface{}) {
	o.Items = &v
}

func (o ListResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Total != nil {
		toSerialize["total"] = o.Total
	}
	if o.TotalReturned != nil {
		toSerialize["totalReturned"] = o.TotalReturned
	}
	if o.Items != nil {
		toSerialize["items"] = o.Items
	}
	return json.Marshal(toSerialize)
}

type NullableListResponse struct {
	value *ListResponse
	isSet bool
}

func (v NullableListResponse) Get() *ListResponse {
	return v.value
}

func (v *NullableListResponse) Set(val *ListResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableListResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableListResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListResponse(val *ListResponse) *NullableListResponse {
	return &NullableListResponse{value: val, isSet: true}
}

func (v NullableListResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


